### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/ANANSE#10]
You function do a lot, but what and how they do it is not explained, making it almost magic unless you delve into the code!

Here are some places in the documentation that might need improvement from you:
- what does each step do? a short explanation in the docs might help.
- what do the output files mean? binding.txt, full_features.txt and {TF}.txt aren't descriptive (to me)
- the ananse influence command requires:
  1. a network
  2. gene expression
  3. differential gene expression with another condition
  
  but what does it do with them? From what I can tell it will infer the ATAC accessbility (and i know it doesn't!).

**Comment by JGASmits** [comment]
For the: "ananse binding" rule it is not clear the genome should be the fastq file of the genome or the folder  containing all the genome files. :)

**Comment by simonvh** [comment]
@JGASmits  Does 81891e5 help?

A list of some concrete things that can be improved.
[ ] A concrete tutorial that explains step by step how to run through the analysis.
[ ] For every subcommand  (`binding`, `network` and `influence`) a piece of text that explains *what* the command does and in short *how* it does this.
[ ] For the enhancers, is it important that the BED is 4 columns? Or is it *at least* for columns? In other words, does it matter if there are more columns?
[ ] Documentation on how such an enhancer file can be created.
[ ] Annotation file, how to get/create it and what is important? Does it need gene names?
[ ] `-k, --keep_detail` what does this mean?

**Comment by JGASmits** [comment]
Yes 81891e5 makes it clear!

For the GRN generation, do you still need to inlude the enhancer file -r as shown in the example? If not perhaps it can be removed from the example script. But if you need to inlcude it still perhaps just repeat the text bellow as an required argument. :)

**Comment by qxuchn** [comment]
See full ANANSE documentation for detailed installation instructions and usage examples. http://anansepy.readthedocs.io
