### ISSUE TITLE
gzipped files fail

### ISSUE THREAD

**Issue by simonvh** [vanheeringen-lab/ANANSE#104]
@siebrenf 

https://github.com/vanheeringen-lab/ANANSE/blob/cd1f3fef7fcf486329a782748da8a099362fcf4f/ananse/network.py#L451

If the `factor_activity.tsv` is gzipped this will fail. This the reason that this test is changed (and should not be changed :))

https://github.com/vanheeringen-lab/ANANSE/blob/62e629cc63fe973a562a02bcccbe454a5711cf0b/tests/continuous_integration/test_05_network.py#L85

**Comment by siebrenf** [comment]
I've unzipped the test activity file and reverted the test!

**Comment by simonvh** [comment]
That's one solution, but how about supporting zipped files in general?
