### ISSUE TITLE
no overlapping transcription factors found

### ISSUE THREAD

**Issue by bitbioJoel** [vanheeringen-lab/ANANSE#110]
When running the ananse influence command I always get the following message (I have tried several datasets now):

"no overlapping transcription factors found between the network file(s) (-s/--source, -t/--target) and the differential expression data (-d/--degenes)"

I can see that TFs within the network files are there and match TFs which are significant in the DGE file. Are there additional filtering steps which could be causing this behaviour?

**Comment by simonvh** [comment]
Hi @bitbioJoel, would you mind sharing the ANANSE version, and the command that you run (which genome, input files etc.)
If you can, please also post the DESeq2 file. Then we can have a look. 
Do you also get the same error if you try the example data?

**Comment by bitbioJoel** [comment]
Hi, details are below

ANANSE version:
Name              Version                        Build       Channel
ananse            0.2.1+28.g3ec07af     pypi_0    pypi

Command:
ananse influence -s /path/to/source.network.txt -t /path/to/target.network.txt -d /path/to/dge.csv -p -o /path/to/output.influence.txt

Genome: hg38 (from genomepy)

DESeq2 file:
[dgenes.csv](https://github.com/vanheeringen-lab/ANANSE/files/6790629/dgenes.csv)

I have tried with the example data, however am unable to complete the network command on the heart data (it is the only data the command fails on I have tried). Therefore haven't tried the influence command on it. I can open a new issue for this if you like?

thanks!

**Comment by simonvh** [comment]
The DESeq2 files doesn't contain all genes it seems. However, that cannot be the problem as there are some significantly changed TFs in there. 

There should be a file called something like `/path/to/output/output.inflence_diffnetwork.txt` after the `ananse influence` run. Can you post the output of:

```
cut -f1 /path/to/output/output.influence_diffnetwork.txt | sort | uniq -c
```

> however am unable to complete the network command on the heart data (it is the only data the command fails on I have tried)

There are some problems with the memory usage of `ananse network`. We're currently working on fix. Once that is available, and it still doesn't work it would be great to have an issue.

**Comment by bitbioJoel** [comment]
There are no output files created from the command, I get this in the terminal but thats it: 

2021-07-09 11:37:38 | INFO | Reading network(s)
2021-07-09 11:39:48 | INFO | Run target score
no overlapping transcription factors found between the network file(s) (-s/--source, -t/--target) and the differential expression data (-d/--degenes)

**Comment by simonvh** [comment]
Ok, there's a few changes to hopefully make more clear what happens. Can you run the following command in your environment, and try `ananse influence` again?

```
pip install git+https://github.com/vanheeringen-lab/ANANSE.git@9219b41
```

From looking at your expression files it seems that your two cell types are relatively close. There was a filtering step in there, that I think is not necessary. Secondly, the file that I asked about is now saved *before* running the influence score calculation. If it still fails, the reason should hopefully be more clear.

**Comment by siebrenf** [comment]
Closing this issue now. Feel free to reopen it if the problem was not fixed!
