### ISSUE TITLE
ananse influence: not enough values to unpack

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/ANANSE#116]
ANANSE influence with zebrafish data. 

The error is caused by the content of the network file. Here is the sorted `head(5)` of the network output file as example:
```
                   tf_target                prob
30149780  gata1a_NC_002333.4  0.7417406048218517
30144133   gata1a_BX649540.1  0.7417310447751986
30141499        gata1a_hbae3  0.7417214847285456
30141238   gata1a_CT027638.1  0.7417119246818925
30129408        gata1a_hbbe3  0.7417023646352395
```

In multiple places, column `tf_target` is "0.5". 

I could add a line to filter these out, but why are they there in the first place? Each tf_target is supposed to be in the form `f"{tf}_{target}"`.

traceback
```
Traceback (most recent call last):
 File "/mbshome/acanosancho/miniconda3/envs/ananse/bin/ananse", line 318, in <module>
  args.func(args)
 File "/mbshome/acanosancho/miniconda3/envs/ananse/lib/python3.9/site-packages/ananse/commands/influence.py", line 20, in influence
  a = ananse.influence.Influence(
 File "/mbshome/acanosancho/miniconda3/envs/ananse/lib/python3.9/site-packages/ananse/influence.py", line 267, in __init__
  G1 = read_network(Gbf, edges=edges)
 File "/mbshome/acanosancho/miniconda3/envs/ananse/lib/python3.9/site-packages/ananse/influence.py", line 49, in read_network
  source, target = vals[1][0].split("_", 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by simonvh** [comment]
Unclear why that would happen. Would be good to find out where it comes from. Three putative sources:

* The `binding.h5` file (specifically the `_factor_activity` table)
* The expression input file(s).
* The gene annotation.

However, is this not a case where the second column is `0.5` and the first is empty? Could be related to #114 ?

**Comment by siebrenf** [comment]
no, these rows have values for both "tf_target" and "prob" columns:
```
tf_target                   0.5
prob         0.6946543868694167
Name: 23251113, dtype: object
```

**Comment by simonvh** [comment]
Huh, weird. You can run `ananse network` with the `--exclude-promoter` **and** `--exclude-enhancer` options. This will generate the network only from the expression file. That should help to pinpoint the issue.

**Comment by siebrenf** [comment]
fixed in develop, thanks to Angela's detective work!
