### ISSUE TITLE
Replace True/False with flags

### ISSUE THREAD

**Issue by simonvh** [vanheeringen-lab/ANANSE#13]
Change all command-line flags tha now require a `True` or `False` argument to flags that change the setting using `store_true` or `store_false`.
For instance the `--keep_detail` argument. 

```
    p.add_argument(
        "-d",
        "--keep_detail",
        dest="detail",
        help="Keep detail files",
        metavar="NAME",
        action="store_true",
        default=False,
    )
```

**Comment by qxuchn** [comment]
Changed. Thanks!
