### ISSUE TITLE
motif case is still an issue

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/ANANSE#151]
using GRCz11 with a pfm file obtained from `gimme motif2factors`, nearly none of of the TFs are found.

excerpt from the log:
```
2021-11-03 20:37:31 | INFO | Using FOXK2 model for foxi1
2021-11-03 20:37:31 | INFO | Using FOXK2 model for foxk2
2021-11-03 20:37:31 | INFO | No related TF found for cebpz, using general model
```

Jaccard saves the day here, but also shows the problem. Again, most TFs fall in the 3rd category.

P.S. If you know how to fix it, please add it to my `fixit` branch.

**Comment by siebrenf** [comment]
I think we currently lack a good method to pick the ortholog model in `PeakPredictor._load_model()` (the jaccard index is good, but not meant for ortholog model selection).

For this we'd need the 1:1 orthologs that `gimme motif2factors` makes.

**Comment by Maarten-vd-Sande** [comment]
The idea of one-to-one orthologs is a scam :fairy: , since it seems like most orthologs are many-to-many (although I never quantified this).

**Comment by Maarten-vd-Sande** [comment]
What's the effect of taking all general on human data? Does it matter much? I don't remember if that was "benchmarked"..

**Comment by siebrenf** [comment]
The sole purpose of the jaccard index  is using the general model less, and it improves Jos' results.

**Comment by simonvh** [comment]
@siebrenf can you post the motif2factors mapping of your `gimme motif2factors` run?

**Comment by simonvh** [comment]
> What's the effect of taking all general on human data? Does it matter much? I don't remember if that was "benchmarked"..

It matters, but not always. For some TFs, a specific model has a lot of improvement, for some it doesn't. We didn't quantify this.

**Comment by siebrenf** [comment]
head of the motif2factors.txt:
```
Motif	Factor	Evidence	Curated
GM.5.0.Sox.0001	sox7	Orthologs	N
GM.5.0.Sox.0001	sox9a	Orthologs	N
GM.5.0.Sox.0001	sox9b	Orthologs	N
GM.5.0.Sox.0001	sox10	Orthologs	N
GM.5.0.Sox.0001	sox12	Orthologs	N
GM.5.0.Sox.0001	sox13	Orthologs	N
GM.5.0.Sox.0001	sox17	Orthologs	N
GM.5.0.Sox.0001	sox18	Orthologs	N
GM.5.0.Homeodomain.0001	tgif1	Orthologs	N
GM.5.0.Homeodomain.0001	FO834857.1	Orthologs	N
```

head of the pfm file (remained the same)
```
>GM.5.0.Sox.0001
0.7213	0.0793	0.1103	0.0891
0.9259	0.0072	0.0062	0.0607
0.0048	0.9203	0.0077	0.0672
0.9859	0.0030	0.0030	0.0081
0.9778	0.0043	0.0128	0.0051
0.1484	0.0050	0.0168	0.8299
>GM.5.0.Homeodomain.0001
0.8870	0.0000	0.0178	0.0951
0.1156	0.2033	0.6629	0.0181
0.0017	0.7452	0.0809	0.1722
0.0011	0.0003	0.0003	0.9983
0.0026	0.0141	0.9721	0.0111
0.0000	0.0189	0.0054	0.9758
0.0006	0.9983	0.0006	0.0006
0.9170	0.0140	0.0046	0.0644
0.2228	0.2421	0.3300	0.2051
0.3621	0.1054	0.2208	0.3116
0.5727	0.0104	0.1741	0.2428
```

[GRCz11.gimme.vertebrate.v5.0.motif2factors.txt](https://github.com/vanheeringen-lab/ANANSE/files/7473579/GRCz11.gimme.vertebrate.v5.0.motif2factors.txt)

the pfm file is appended with .txt, otherwize git wouldnt post it:
[GRCz11.gimme.vertebrate.v5.0.pfm.txt](https://github.com/vanheeringen-lab/ANANSE/files/7473582/GRCz11.gimme.vertebrate.v5.0.pfm.txt)

**Comment by siebrenf** [comment]
If the motif2factors command would also output a conversion table like `FOXK2    foxk2`, that could be used to select the ortholog model. Does that make sense?

**Comment by simonvh** [comment]
I'm not sure! Most TFs will not have 1-to-1 ortholog. 
If there is a clear ortholog, or a limited set of orthologs then picking a related model with the Jaccard based approach would work. I'm not sure yet how much of a problem this is?

**Comment by simonvh** [comment]
I don't get why it doesn't work as is:
CEBPA motifs: `['GM.5.0.Forkhead.0001', 'GM.5.0.bZIP.0046', 'GM.5.0.Unknown.0037', 'GM.5.0.bZIP.0069', 'GM.5.0.bZIP.0083']`
cebpz motifs: `['GM.5.0.bZIP.0031', 'GM.5.0.bZIP.0046', 'GM.5.0.bZIP.0052', 'GM.5.0.bZIP.0069', 'GM.5.0.bZIP.0083']`

Jaccard index: `0.43`

Therefore, the CEBPA model should/could have been picked for cebpz.

You do supply both files to ANANSE, right?

**Comment by siebrenf** [comment]
yes! that's what I suggested in the comment above.

Here is why this didn't happen now:
- the motif2factors contains `cebpz` and `cebpa`.
- the jaccard index indeed links these two motifs together
    - here is the head of the nearest source: `{'cebpz': 0, 'si_ch1073-412h12.3': 0.0, 'cebpa': 0.5, 'nfyba': 0.875}` (its inverted, so lower is better).
- so 'cebpa' would indeed be used if a model would have been found. However, we dont have a model for 'cebpa', only a model for 'CEBPA'.

So we need a system to get the ortholog model in case we use a non-human motif2factors

**Comment by siebrenf** [comment]
and yes, I used this model in the run. here is the log.
[GRCz11_binding.log.txt](https://github.com/vanheeringen-lab/ANANSE/files/7473879/GRCz11_binding.log.txt)

spoiler:
```
No related TF found for cebpa, using general model
```

**Comment by simonvh** [comment]
> So we need a system to get the ortholog model in case we use a non-human motif2factors

But that is already the case! It should link to the human factors, so something is wrong here! Which version/branch/commit of ANANSE are you using?

**Comment by siebrenf** [comment]
fixit

**Comment by siebrenf** [comment]
aaah. i might have broken it @simonvh. brb

**Comment by siebrenf** [comment]
I'm sorry all. There was a section of code that I was sure of it did nothing. 🙈 
It indeed did nothing in the immediate code section, but it did fix exactly this issue.

`{'cebpz': 0, 'si_ch1073-412h12.3': 0.0, 'CEBP': 0.19, 'cebpa': 0.5, 'CEBPA': 0.57, 'CEBPZ': 0.8,...`
