### ISSUE TITLE
ANANSE binding error

### ISSUE THREAD

**Issue by tzhu-bio** [vanheeringen-lab/ANANSE#158]
![image](https://user-images.githubusercontent.com/54537420/147820681-2394c141-30bf-486f-921d-ee5b29a8e004.png)

This error like [https://github.com/vanheeringen-lab/ANANSE/issues/94](url)

And the version is **ananse v0+unknown**

![image](https://user-images.githubusercontent.com/54537420/147820831-c6c3d748-9358-4331-b033-d7c2c89f9077.png)

**Comment by siebrenf** [comment]
Hi tzhu, 
I think something went wrong during your installation. If the installation works, the ananse version should start with `v0.3`.

P.S. I have been trying to make ANANSE easier to use. If you wish to try this version, you can install the develop branch with:
```
wget https://github.com/vanheeringen-lab/ANANSE/blob/develop/requirements.yaml -O ananse_dev.yaml
conda env create -f ananse_dev.yaml
conda activate ananse_dev
pip install git+https://github.com/vanheeringen-lab/ANANSE.git@develop
```
(if you're not using conda, you can replace the two conda lines with `pip install -r ananse_dev.yaml`)

**Comment by siebrenf** [comment]
Closing this issue now. Feel free to reopen it if the problem was not fixed!
