### ISSUE TITLE
readthedocs broken links

### ISSUE THREAD

**Issue by malcook** [vanheeringen-lab/ANANSE#161]
I find on https://anansepy.readthedocs.io/en/master/faq/ that the link to https://anansepy.readthedocs.io/en/latest/input_data/#enhancer-data returns 404

Is this resource elsewhere available?

**Comment by siebrenf** [comment]
Yes! The link should direct you [here](https://anansepy.readthedocs.io/en/master/input_data/#enhancer-activity). 

Thank you for reporting this, I've fixed it in the develop branch!

**Comment by malcook** [comment]
Great.  Note: there is another 404 at https://anansepy.readthedocs.io/en/latest/input_data/#motif-database

**Comment by siebrenf** [comment]
Yep, thanks again! Turns out there was a `/` in the reference that wasn't supposed to be there! 

Check it out [here](https://anansepy.readthedocs.io/en/master/input_data/#motif-database).

**Comment by malcook** [comment]
thanks
