### ISSUE TITLE
Issue with motif2factors before ANANSE

### ISSUE THREAD

**Issue by lynnyummy** [vanheeringen-lab/ANANSE#185]
I am trying to use ANANSE to analysis my ATAC-seq and RNA-seq data, however I am stuck at the very first step of "motif2factors".

Because  I am using an unpublished genome, so I need to convert the motifs2factors in my species. The following is my commands,

`gimme motif2factors  --new-reference my_species --database db --ortholog-references ref_1 ref_2 ref_3  --outdir my_species _motif2factors_ref --tmpdir my_species _whole_ref_temp`

It ran normally in "orthofinder" step, however it reported error after this
```
"File "/data/home/.conda/envs/gimme/lib/python3.9/site-packages/gimmemotifs/utils.py", line 102, in pfmfile_location
    raise ValueError("Motif file {} not found".format(infile))
ValueError: Motif file db not found"
```

I am confused, cause based on the command you suggest (gimmemotif2factors --new-reference danRer11--outdir mynewdatabase from https://anansepy.readthedocs.io/en/master/input_data/), there is no flag for the motif, I am not sure in which step I need to put the motif into the analysis of motif2factor?

and I also ran the `gimmemotif2factors --new-reference danRer11--outdir mynewdatabase`, it reported error,
`File "/data/home/.conda/envs/gimme/lib/python3.9/site-packages/gimmemotifs/orthologs.py", line 417, in make_motif2factors
    with open(f"{prefix}.motif2factors.txt", "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'mynewdatabase/danRer11.gimme.vertebrate.v5.0.motif2factors.txt'`

**Comment by siebrenf** [comment]
Hey @lynnyummy,

To use a database (other  than the default gimme.vertebrates.v5.0) you specify a database name (without file suffices). For example `--database JASPAR2020_plant`.

The list of databases can be found [here](https://github.com/vanheeringen-lab/gimmemotifs/tree/master/data/motif_databases)!

**Comment by lynnyummy** [comment]
> Hey @lynnyummy,
> 
> To use a database (other than the default gimme.vertebrates.v5.0) you specify a database name (without file suffices). For example `--database JASPAR2020_plant`.
> 
> The list of databases can be found [here](https://github.com/vanheeringen-lab/gimmemotifs/tree/master/data/motif_databases)!

Hi, Thanks for your reply! I would have a try again!
Thank you very much!
