### ISSUE TITLE
ananse network, genomepy hg38

### ISSUE THREAD

**Issue by JGASmits** [vanheeringen-lab/ANANSE#20]
When trying to run Ananse-network using a genomepy downloaded version of hg38, it crashes due to: 'ERROR: chrom "chr10_KN196480v1_fix" not found in genome file. Exiting.'.

I've told my student to use the annotation file : "hg38_genes.bed' , that I downloaded a while back from the ananse github (but I could be mistaken). Now it seems to run. However I think its good to check that it works with genomepy genome and annotation files.

Gr Jos

**Comment by JGASmits** [comment]
Alternatively, if you explain in the docs how to generate the propper annotation file from the one downloaded from genomepy that would also work. Right now there is a link in the docs, but no explanation. :)

**Comment by simonvh** [comment]
I think this is a difficult problem, as the annotation from genomepy does not necessarily contain gene names (HGNC symbols), which are necessary now to link motifs to TFs. The solution for now is to update the documentation and have annotation files specifically mentioned and available for download. I think we should include `hg38`, `hg19` and `mm10`. @qxuchn can you take care of this?

In the future I have planned automatic gene symbol mapping in genomepy which could solve this problem maybe.
