### ISSUE TITLE
differential expression data .tsv not .csv

### ISSUE THREAD

**Issue by JGASmits** [vanheeringen-lab/ANANSE#21]
Small things, but whenever I encounter them I just make a issue so its clear where in the docs there are any mistakes left. 
In the documentation the example differential genes, the example input is a .csv file. However at the input data section of the docs the example is a .tsv. 

Furthermore many of the links in the documentation to examples are dead giving a 404 error.

**Comment by siebrenf** [comment]
the command line example for ANANSE influence now has a `.tsv` file on the develop branch :)
