### ISSUE TITLE
ananse binding genome error

### ISSUE THREAD

**Issue by connorrogerson** [vanheeringen-lab/ANANSE#23]
When trying to run ananse binding, I get this error:

ananse binding -r counts.bed -o ananse_binding/H3K27ac.txt -g mm10 -p "/home/cjr78/miniconda3/pkgs/gimmemotifs-0.14.4-py37h516909a_0/lib/python3.7/site-packages/data/motif_databases/gimme.vertebrate.v5.0.pfm"
Traceback (most recent call last):
  File "/home/cjr78/miniconda3/envs/gimme/bin/ananse", line 286, in <module>
    args.func(args)
  File "/home/cjr78/miniconda3/envs/gimme/lib/python3.7/site-packages/ananse/commands/binding.py", line 21, in binding
    genome=args.genome, gene_bed=args.annotation, pfmfile=args.pfmfile
  File "/home/cjr78/miniconda3/envs/gimme/lib/python3.7/site-packages/ananse/binding.py", line 40, in __init__
    self.gsize = g.props["sizes"]["sizes"]
AttributeError: 'Genome' object has no attribute 'props'

My genome is installed via genomepy and works with gimmemotifs. Tried to specific the .fa file but the same error.

**Comment by siebrenf** [comment]
Hey @connorrogerson,

this issue occurs with an older version of `ANANSE`. I think it is fixed by updating to v0.1.3

**Comment by simonvh** [comment]
Just to confirm: @connorrogerson did the update fix this? Then we can close this issue.

**Comment by connorrogerson** [comment]
Yes update fixed this!
