### ISSUE TITLE
ananse network error

### ISSUE THREAD

**Issue by connorrogerson** [vanheeringen-lab/ANANSE#25]
When running ananse network I've supplied a single gene expression file formatted as described, however I get this error:

ananse network -e tpm.txt -b binding_output.txt -o network_output.txt -a ~/.local/share/genomes/mm10/mm10.annotation.bed.gz -g mm10 --include-promoter

2020-06-18 16:39:02.214 | INFO     | ananse.network:run_network:746 - Read data
2020-06-18 16:39:06.236 | INFO     | ananse.network:run_network:756 - Aggregate binding
[########################################] | 100% Completed |  5min 38.6s
2020-06-18 16:50:44.196 | INFO     | ananse.network:run_network:759 - Join expression
Traceback (most recent call last):
  File "/home/cjr78/miniconda3/envs/ananse/bin/ananse", line 326, in <module>
    args.func(args)
  File "/home/cjr78/miniconda3/envs/ananse/lib/python3.7/site-packages/ananse/commands/network.py", line 30, in network
    args.binding, args.fin_expression, args.corrfiles, args.outfile
  File "/home/cjr78/miniconda3/envs/ananse/lib/python3.7/site-packages/ananse/network.py", line 761, in run_network
    expression_file = self.get_expression(fin_expression, features)
  File "/home/cjr78/miniconda3/envs/ananse/lib/python3.7/site-packages/ananse/network.py", line 453, in get_expression
    df[col + ".scale"] = minmax_scale(df[col])
  File "/home/cjr78/miniconda3/envs/ananse/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 502, in minmax_scale
    dtype=FLOAT_DTYPES, force_all_finite='allow-nan')
  File "/home/cjr78/miniconda3/envs/ananse/lib/python3.7/site-packages/sklearn/utils/validation.py", line 586, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.

Since the last call is 'join expression', I thought it might be to do with the expression file. Using the example expression file, the same error occurs.

**Comment by simonvh** [comment]
@connorrogerson Just to double-check: can you post the `head` of  `tpm.txt`, `binding_output.txt`,  and `network_output.txt`. And also the (zcatted) `head` of ` ~/.local/share/genomes/mm10/mm10.annotation.bed.gz`. My suspicion is that this has to do with non-matching gene names. This is something that we're still planning on making more robust, it's a bit finicky at the moment. 

@qxuchn I think we should add recommended annotation (with gene names) for at least hg19, hg38 and mm10 and clearly describe that in the docs.

**Comment by qxuchn** [comment]
Hi @connorrogerson, Could you try this bed file for mm10? https://github.com/vanheeringen-lab/ANANSE/blob/develop/ananse/db/mm10.gene.bed

**Comment by connorrogerson** [comment]
@simonvh Head of files are:
tpm.txt
```
target_id       tpm
0610005C13Rik   0.667612789
0610007P14Rik   114.0300633
0610008F07Rik   0.977771211
0610009B14Rik   0
0610009B22Rik   186.4699173
0610009D07Rik   489.9146919
0610009E02Rik   0.813321198
0610009L18Rik   2.715324334
0610009O20Rik   813.1485296
```

binding_outpt.txt
```
factor  enhancer        zscore  peakRPKMScale   binding
AHCTF1  chr10:116260951-116261151       0.3879186367876717      0.5484041141710598      0.45728265648085925
AHCTF1  chr10:120553024-120553224       0.3244474705334235      0.10154843213168396     0.016056064952112047
AHCTF1  chr10:121796103-121796303       -0.5983090240911805     0.2466071260962689      0.034709375982019494
AHCTF1  chr10:121796547-121796747       0.8269014471786049      0.2732615726474855      0.08695641435772322
AHCTF1  chr10:127879329-127879529       -0.3259124698237299     0.12752296157519485     0.014398125342330703
AHCTF1  chr10:128149684-128149884       -0.9020065228610537     0.29979629920356604     0.0466320121059178
AHCTF1  chr10:128965011-128965211       -0.1723569335518177     0.4242311341821319      0.17518178076387075
AHCTF1  chr10:22306646-22306846 -0.3887967828729639     0.2028755814800852     0.026615196557074387
AHCTF1  chr10:5289364-5289564   -0.3266659122665533     0.01726138418795331    0.005532125110161681
```

mm10.annotation.bed.gz
```
chr1    3073252 3074322 ENSMUST00000193812.1    0       +       3073252 307325201       1070,   0,
chr1    3102015 3102125 ENSMUST00000082908.1    0       +       3102015 310201501       110,    0,
chr1    3205900 3216344 ENSMUST00000162897.1    0       -       3205900 320590002       1417,2736,      0,7708,
chr1    3206522 3215632 ENSMUST00000159265.1    0       -       3206522 320652202       795,2194,       0,6916,
chr1    3214481 3671498 ENSMUST00000070533.4    0       -       3216021 367134803       2487,200,947,   0,207220,456070,
chr1    3365730 3368549 ENSMUST00000195335.1    0       -       3365730 336573001       2819,   0,
chr1    3375555 3377788 ENSMUST00000192336.1    0       -       3375555 337555501       2233,   0,
chr1    3464976 3467285 ENSMUST00000194099.1    0       -       3464976 346497601       2309,   0,
chr1    3466586 3513553 ENSMUST00000161581.1    0       +       3466586 346658602       101,149,        0,46818,
chr1    3512450 3514507 ENSMUST00000192973.1    0       -       3512450 351245001       2057,   0,
```

So it seems that the annotation file has ensembl gene names rather than gene symbols (this annotation file was taken from gimmemotifs).

@qxuchn I've downloaded that bed file and I get a new error:

```
2020-06-23 10:18:06.179 | INFO     | ananse.network:run_network:746 - Read data
Traceback (most recent call last):
  File "/home/cjr78/miniconda3/envs/ananse/bin/ananse", line 326, in <module>
    args.func(args)
  File "/home/cjr78/miniconda3/envs/ananse/lib/python3.7/site-packages/ananse/commands/network.py", line 30, in network
    args.binding, args.fin_expression, args.corrfiles, args.outfile
  File "/home/cjr78/miniconda3/envs/ananse/lib/python3.7/site-packages/ananse/network.py", line 751, in run_network
    prom = self.get_promoter_dataframe(filter_bed)
  File "/home/cjr78/miniconda3/envs/ananse/lib/python3.7/site-packages/ananse/network.py", line 136, in get_promoter_dataframe
    b = b.flank(l=1, r=0, s=True, g=self.gsize).slop(  # noqa: E741
  File "/home/cjr78/miniconda3/envs/ananse/lib/python3.7/site-packages/pybedtools/bedtool.py", line 917, in decorated
    result = method(self, *args, **kwargs)
  File "/home/cjr78/miniconda3/envs/ananse/lib/python3.7/site-packages/pybedtools/bedtool.py", line 401, in wrapped
    decode_output=decode_output,
  File "/home/cjr78/miniconda3/envs/ananse/lib/python3.7/site-packages/pybedtools/helpers.py", line 455, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError:
Command was:

        bedtools flank -s -r 0 -l 1 -i /rds/user/cjr78/hpc-work/ATAC/ananse/ananse_network/mm10.genes.bed -g /home/cjr78/.local/share/genomes/mm10/mm10.fa.sizes

Error message was:
Differing number of BED fields encountered at line: 6498.  Exiting...
```

**Comment by qxuchn** [comment]
Could you put your command what are you runing here?

**Comment by connorrogerson** [comment]
@qxuchn 
`ananse network -b binding_output.txt -e tpm.txt -o full_network.txt -g mm10 -a mm10.genes.bed --include-promoter`

**Comment by qxuchn** [comment]
Could you send me your `mm10.fa.sizes` file?

**Comment by connorrogerson** [comment]
```
chrY_JH584303_random    158099
chrY_JH584302_random    155838
chrY_JH584301_random    259875
chrY_JH584300_random    182347
chrY    91744698
chrX_GL456233_random    336933
chrX    171031299
chrUn_JH584304  114452
chrUn_GL456396  21240
chrUn_GL456394  24323
chrUn_GL456393  55711
chrUn_GL456392  23629
chrUn_GL456390  24668
chrUn_GL456389  28772
chrUn_GL456387  24685
chrUn_GL456385  35240
chrUn_GL456383  38659
chrUn_GL456382  23158
chrUn_GL456381  25871
chrUn_GL456379  72385
chrUn_GL456378  31602
chrUn_GL456372  28664
chrUn_GL456370  26764
chrUn_GL456368  20208
chrUn_GL456367  42057
chrUn_GL456366  47073
chrUn_GL456360  31704
chrUn_GL456359  22974
chrUn_GL456239  40056
chrM    16299
chr9    124595110
chr8    129401213
chr7_GL456219_random    175968
chr7    145441459
chr6    149736546
chr5_JH584299_random    953012
chr5_JH584298_random    184189
chr5_JH584297_random    205776
chr5_JH584296_random    199368
chr5_GL456354_random    195993
chr5    151834684
chr4_JH584295_random    1976
chr4_JH584294_random    191905
chr4_JH584293_random    207968
chr4_JH584292_random    14945
chr4_GL456350_random    227966
chr4_GL456216_random    66673
chr4    156508116
chr3    160039680
chr2    182113224
chr1_GL456221_random    206961
chr1_GL456213_random    39340
chr1_GL456212_random    153618
chr1_GL456211_random    241735
chr1_GL456210_random    169725
chr19   61431566
chr18   90702639
chr17   94987271
chr16   98207768
chr15   104043685
chr14   124902244
chr13   120421639
chr12   120129022
chr11   122082543
chr10   130694993
chr1    195471971

```

**Comment by qxuchn** [comment]
Could you download the `bed` file again? I can run your example data in my computer.

**Comment by connorrogerson** [comment]
Ran fine this time. I think I must have only downloaded half of the bed file for some reason! Thanks for your help.
