### ISSUE TITLE
auto update docs

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/ANANSE#39]
If I got it correctly, docs are controlled by `mkdocs.yml`, which compiles stuff in `docs/`. 
Is there a github action that can compile these docs on a PR?

Bonus: can we put `mkdocs.yml` in the `docs/` directory too?

**Comment by Maarten-vd-Sande** [comment]
It already runs with a webhook to readthedocs. Best not to touch that I think

**Comment by simonvh** [comment]
Docs will autobuild on readthedocs indeed :)
