### ISSUE TITLE
filtering

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/ANANSE#41]
Multiple functions filter by gene names (binding and network at least). 
I'd like to know where so we can discuss where and how the filtering should be performed.

If it is required in multiple places we can maybe add a filter function to `utils.py`.

In ANANSE binding, this happens in `enhancer_binding.py`'s `filter_transcription_factors()` (this used to be `binding.py`'s `clear_tfs()`)
However, we could also filter earlier, on gimme's `motifs.pfm` file, which would reduce the scanning time as well!

**Comment by simonvh** [comment]
This should be fixed in the new release :).
