### ISSUE TITLE
Pairwise comparison of multiple time points

### ISSUE THREAD

**Issue by adeben1** [vanheeringen-lab/ANANSE#49]
The way I want to use ANASE is comparing GRNs from an early sample vs an old sample from the same tissue. I have RNA-seq and ATAC-seq for multiple time points, do you see reasonable looking for transcription factors doing pairwise comparison? I wanted to perform time point 1 vs time point 0, time point 2 vs time point 1, and so on. I would expect to see if there are a common TF program across all time points or if they are different in each step.

**Comment by simonvh** [comment]
Hi @adeben1, yes certainly! This is also one of our interests. The way I would see this work is to create networks for every timepoint, and then compare them using the influence score (`ananse influence`). This would highlight TFs that are putative regulators of the differential networks. This is what we have done, for instance in an embryonic developmental time course of _Xenopus tropicalis_, and also in human _in vitro_ time courses. This seems to work well.
