### ISSUE TITLE
Biological replicates

### ISSUE THREAD

**Issue by adeben1** [vanheeringen-lab/ANANSE#50]
When reading the docs from Github, the enhancer command uses a file called "KRT_H3K27ac_rep1.bam". Since I haven't seen any "rep2.bam" I wonder if there is a way to handle biological replicates for the peaks data.

**Comment by siebrenf** [comment]
Currently no, but you can make it work with one of these methods:
- You could merge the bam files. 
- You can try the experimental version of ANANSE, here are the steps:
    - clone the repo from git 
    - checkout development branch 
    - install a development environment with conda: conda env create -n ananse_dev -f requirements.yaml 
    - activate the environment with conda activate ananse_dev 
    - install ANANSE with python setup.py develop
