### ISSUE TITLE
custom genome ananse network

### ISSUE THREAD

**Issue by adeben1** [vanheeringen-lab/ANANSE#55]
Trying to run ananse network using an assembly not from genomepy gave me a problem. I encountered the error ```ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.``` after "Join expression" is printed, which in a former issue was related to gene names. 

Previously to ananse network, I consulted Maarten and he suggested and share with me a code to generate a motif2factors file for my gene ids. The following motif2factors file contains gene names from orthologous genes to the original motif2factors file but from different assemblies. Here it is:

```
Motif	Factor	Evidence	Curated
GM.5.0.Sox.0001	SOX9A	Orthologs	N
GM.5.0.Sox.0001	SOX9B	Orthologs	N
GM.5.0.Sox.0001	AL929022.1	Orthologs	N
GM.5.0.Sox.0001	SOX18	Orthologs	N
GM.5.0.Sox.0001	SOX7	Orthologs	N
GM.5.0.Sox.0001	SOX4A	Orthologs	N
GM.5.0.Sox.0001	SOX4B	Orthologs	N
GM.5.0.Homeodomain.0001	TGIF1	Orthologs	N
GM.5.0.Homeodomain.0001	TGIF2	Orthologs	N
GM.5.0.Mixed.0001	Nfu_g_1_013515	Orthologs	N
```
I filtered it to keep those lines containing my gene names (I also removed the "_" and transformed to uppercase, suggested by Maarten):

```
Motif	Factor	Evidence	Curated
GM.5.0.Mixed.0001	NFUG1013515	Orthologs	N
GM.5.0.bHLH.0001	NFUG1022543	Orthologs	N
GM.5.0.bHLH.0001	NFUG1006036	Orthologs	N
GM.5.0.C2H2_ZF.0001	NFUG1013515	Orthologs	N
GM.5.0.bZIP.0002	NFUG1018863	Orthologs	N
```

Then, I used this command:
```
ananse binding -r enhancer.bed -o binding.txt -g Nfu_20150522.genes_20140630/Nfu_20150522.softmasked_genome.fa -t ATAC -p Nfu_20150522.gimme.vertebrate.v5.0.pfm -f ../tf_nfu.txt --unremove-curated --include-notfs
```
Resulting binding.txt file

```
factor	enhancer	zscore	log10_peakRPKM	binding
NFUG1013515	scaffold01062:16192-16392	-0.07880385405158605	0.4758762314880969	0.0936134202605538
NFUG1013515	sgr01:12854699-12854899	-0.17834431235782186	0.7764678514396647	0.15454978522361046
NFUG1013515	sgr01:23638699-23638899	0.6767994812144132	1.2505841736269574	0.45572099669473215
NFUG1013515	sgr01:38279565-38279765	-1.3940636981458527	1.1807659445934546	0.1686181312937036
```

Finally, I show the ananse network command which popped up the error I described at the begining and files used:

```
ananse network -e tpm.txt -b binding.txt -o net.txt -a annotation.bed -g Nfu_20150522.genes_20140630/Nfu_20150522.softmasked_genome.fa --exclude-promoter --include-enhancer
```

tpm.txt

```
target_id	tpm
NFUG1013515	5.3
NFUG1000002	5.29503121149557
NFUG1000003	19.6412583379942
NFUG1000004	9.03547608404788
NFUG1000005	31.93858899898
```
annotation.bed

```
scaffold00001	10325	22501	NFUG1003772	0	-	10325	22501	0	7	16,89,44,283,79,27,23,	0,1123,2270,8520,11102,12103,12153,
scaffold00001	22086	26253	NFUG1003773	0	+	22675	25081	0	3	910,499,1186,	0,1701,2981,
scaffold00001	26043	273596	NFUG1003771	0	-	26043	273596	0	12	45,26,79,173,258,186,150,209,196,6,123,124,	0,120,231,397,2641,8138,91840,111272,143840,203384,244535,247429,
```
I don't know where the problem could be, I believe my custom gene ids are overlapping in all files.

**Comment by adeben1** [comment]
I forgot to mention that if I replace all my gene ids with HGCN symbols in all files, then it works. However I would like not to use this method with my data.

**Comment by simonvh** [comment]
I think this is because the current version of ananse filters on human gene name. Which it shouldn't and this will be fixed in the upcoming version. In the meantime we can probably fix this temporarily. 

Find you conda env directory using `conda env list`. In my case this is `/vol/mbconda/heeringen/envs/ananse`.

```
cut -f2 <your_motif2factors.txt> | sort -u >> mv $ENV_DIR/llib/python3.8/site-packages/ananse/db/tfs.txt
 $ENV_DIR/llib/python3.8/site-packages/ananse/db/tfs.human.txt 
cp my_tfs.txt $ENV_DIR/llib/python3.8/site-packages/ananse/db/tfs.txt




/vol/mbconda/heeringen/envs/ananse_dev/

**Comment by adeben1** [comment]
I still get the same error. This time I generated dummy files containing a transcription factor (with my custom gene id) which is also in ```~/miniconda3/envs/ananse/lib/python3.8/site-packages/ananse/db/tfs.txt ``` but nothing change.

**Comment by Maarten-vd-Sande** [comment]
@simonvh I think what you propose is already tackled by `--unremove-curated --include-notfs`

**Comment by simonvh** [comment]
I think the new version of ANANSE (0.2.0) fixes this, and should make it possible to run ANANSE on species other than human. Feel free to re-open if issues still occur.
