### ISSUE TITLE
ananse binding: what does -d do?

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/ANANSE#6]
The docs and `--help` message of `ananse binding` both state that the `-d` flag keeps the detail files. 
1) Where do these go?
2) What are they?

question 1 might be solved by making the `-o` flag a directory instead of a file.

**Comment by qxuchn** [comment]
I will improve it late.

**Comment by simonvh** [comment]
I think this is now obsolete given the latest version of the commands? Closing.
