### ISSUE TITLE
ananse network: correlation file

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/ANANSE#7]
where does the correlation file come from? what is it, and how can I make one for my assembly/assemblies?

**Comment by qxuchn** [comment]
The correlation file is a file that include the expression correlation among every TFs and every genes. In the README file, there is a example file of human: `All gene correlation file, the human gene expression correlation can be found at here.`. For other species, you should made it yourself.

**Comment by siebrenf** [comment]
How could I make it myself?

**Comment by siebrenf** [comment]
![image](https://user-images.githubusercontent.com/48289046/78536295-e750ad00-77ed-11ea-94a9-aa324672519e.png)

**Comment by siebrenf** [comment]
whoops too fast. I'll keep this open to remind you about the documentation :)

**Comment by qxuchn** [comment]
Thanks! It is in `Optional arguments` now.

**Comment by JGASmits** [comment]
How does the inclusion/exclusion of the correaltion file impact the results? Do you advice to still include it when running Ananse with human data?

**Comment by qxuchn** [comment]
I still need to test it myself.
