### ISSUE TITLE
Is ananse network supposed to have an output option?

### ISSUE THREAD

**Issue by jonasungerback** [vanheeringen-lab/ANANSE#79]
Hello,

I have just installed the latest conda version of ananse and when I try to run:

`ananse network -b cDC1.F5_enhancers.binding/binding.tsv -e tpm_files/cDC1.ananse.tpm.txt -n 4` 

I get the following error: 

`Traceback (most recent call last):
  File "/opt/anaconda3/envs/gimme/bin/ananse", line 306, in <module>
    args.func(args)
  File "/opt/anaconda3/envs/gimme/lib/python3.8/site-packages/ananse/commands/network.py", line 31, in network
    outfile=args.outfile,
AttributeError: 'Namespace' object has no attribute 'outfile`

However, I cannot see an output option as an argument to `ananse network` and when I try that I get an error as well (but it seems in older instructions like there used to exists such an option).

Am I just missing something really simple?

Best,

Jonas

**Comment by simonvh** [comment]
You seem to be completely correct! How embarrassing that is... We streamlined the command line, but were a little to rigorous it seems. We will release a new version on conda, but that will take a little while. In your environment you can run the following command to install the bugfix release:

```
pip install git+https://github.com/vanheeringen-lab/ANANSE.git@v0.2.1
```

**Comment by jonasungerback** [comment]
Thank you! Now that part is running nicely.
