### ISSUE TITLE
ananse influence: AttributeError: 'Namespace' object has no attribute 'fin_expression' 

### ISSUE THREAD

**Issue by jonasungerback** [vanheeringen-lab/ANANSE#83]
Hello again and sorry for my spams :)

When I updated my local environment with `pip install git+https://github.com/vanheeringen-lab/ANANSE.git@v0.2.1` ananse network run smoothly but I have now encountered a problem when running `ananse influence -s cDC1.F5_enhancers.binding/cDC1.network.txt -t cDC2.F5_enhancers.binding/cDC2.network.txt -d log2fc_files/cDC1vscDC2.ananse.log2fc.txt -o influence_out/cDC1TOcDC2.out.txt -n 12`

I get the following error:

`2021-06-03 14:10:03 | INFO | Reading network(s)
Traceback (most recent call last):
  File "/opt/anaconda3/envs/gimme/bin/ananse", line 317, in <module>
    args.func(args)
  File "/opt/anaconda3/envs/gimme/lib/python3.8/site-packages/ananse/commands/influence.py", line 29, in influence
    args.plot, args.fin_expression
AttributeError: 'Namespace' object has no attribute 'fin_expression`

So when I look at lines 28-30 it says `    a.run_influence(
        args.plot, args.fin_expression
    )  # -p and --expression (HGNC gene names and TPM)`

Note that it only says that here when ananse is updated with the command above but in the current github instance of influence.py that does not seem to be the case. 

Should something have been included in the network files that are not there so ananse network didn't run properly. -p is the plot option I assume but where does --expression come from? Am I just missing something?

Best,
Jonas

**Comment by Maarten-vd-Sande** [comment]
This is embarrassing!

![giphy](https://user-images.githubusercontent.com/15323399/120655631-2bd3e900-c483-11eb-9809-1581746335d7.gif)

I'm taking a look right now

**Comment by Maarten-vd-Sande** [comment]
Hi @jonasungerback,

Not entirely sure, but if you don't mind you can try replacing the `args.fin_expression` into `args.expression`. We did a major rehaul from version 1 to version 2, and we are now realizing that not everything gets tested properly.

**Comment by jonasungerback** [comment]
Thanks. Worked like a charm. That one I should have been able to figure out for myself but if someone else run into it, at least it is here. Have a good weekend and thanks for awesome tools.

**Comment by Maarten-vd-Sande** [comment]
Thanks for reporting! Ideally you would not have to patch any code :smile: and we will make sure this is fixed soon! Is it okay if we leave this open until this is fixed in the new release?

**Comment by jonasungerback** [comment]
Of course!

**Comment by Maarten-vd-Sande** [comment]
@jonasungerback this should be fixed in the newest release (0.2.2). Thanks for reporting this :smile:
