### ISSUE TITLE
ananse influence: command line

### ISSUE THREAD

**Issue by siebrenf** [vanheeringen-lab/ANANSE#9]
The docs refer to 'first cell' and 'second cell'. Do you mean 'output from command x/y', or sequencing samples?

**Comment by qxuchn** [comment]
I don't understand your question here.

**Comment by siebrenf** [comment]
in the docs, you wrote `The network in second cell.` and `The network in first cell (optional).`. Do you mean any two cells or samples that you processed with `ananse binding` and `ananse network` before?

**Comment by qxuchn** [comment]
Yes. You need using `ananse binding` and `ananse network` in two cell types/tissues, and got two networks. Then run `ananse influence` with two networks(`source` and `target` network now).

**Comment by simonvh** [comment]
@siebrenf Is this more clear with the current version of the docs? https://anansepy.readthedocs.io/en/master/command-line_reference/#infer-tf-influence-score-ananse-influence If so, we can close this issue.

**Comment by siebrenf** [comment]
The develop branch is looking clearer yes, but here are a few more points that I think should be explained:
- only the target network is required. What happens if you add only 1 network?
- expression data is optional. What is the effect of (not) adding it?
- edges is set to 100000 by default. I would mention this default number. Also please mention what the effect is of changing the number.
- what is happening in the generated plot? (I checked this one: the size of the points in linearly dependent on the number of direct interactions). P.S. @CarlottaHS came with this excellent question

**Comment by andrewbcaldwell** [comment]
I had another question related to this topic, it's not entirely clear from the docs how one should generate the degenes.tsv list. Assuming the source cell is celltype_1 (e.g. FB) and the target cell is celltype_2 (e.g. KRT), would FB2KRT_degenes.tsv be celltype_1 relative to celltype_2 (source relative to target) or celltype_2 relative to celltype_1 (target relative to source)? My inclination would be the latter, but from the example tpm.txt and degenes.csv you provide it looks like the former. Could you clarify which one it is? Thanks!

**Comment by simonvh** [comment]
Closing. The documentation is updated for the new version, information about the degenes is now specified in https://anansepy.readthedocs.io/en/master/input_data/.
